# Uncomment this line to define a global platform for your project
 platform :ios, '9.2'

target 'Pop' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'pop'


  # Pods for Pop

end
